version: '3'

services:
  app_test:
    build: .
    command: sh ./start-test.sh
    depends_on:
      - postgres_test
    env_file:
      - .env.test
    volumes:
      - .:/app

  postgres_test:
    image: postgres:15-alpine
    env_file:
      - .env.test

    volumes:
      - pg-test:/var/lib/postgresql/data

volumes:
  pg-test:
