version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env    
    volumes:
      - .:/app

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432' # expose db port for local use
    env_file:
      - .env

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: